### ISSUE TITLE
Network error 

### ISSUE THREAD

**Issue by eekbert** [dinerocoin/copay-dinero#1]
My Dinero iphone wallet no longer syncs... keeps saying "network error". Has there been a change to Dinero? or a fork?.. regards, Eino

**Comment by gumpz** [comment]
Same here...using android app wallet, network error

**Comment by Zendt** [comment]
There is no changes or Forks. Bitcore Wallet Services has been turned off for cost-cutting reasons. Also, insights explorer is not working as there was an issue with the web certificate that has been recently changed.

**Comment by eekbert** [comment]
Ok, I have a few thousand coins in this wallet. Is there a way to send them to a desktop wallet? Or are they lost? Thanks for the reply, regards Eino

**Comment by eekbert** [comment]
So, please turn on the Bitcore Wallet services just for a short time so that I can move my coins to a desktop wallet, PLEASE!
